// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IIcomoonFreeSpinner: typeof import('virtual:vite-icons/icomoon-free/spinner')['default']
    IIcomoonFreeSpinner5: typeof import('virtual:vite-icons/icomoon-free/spinner5')['default']
  }
}

export { }
